language: rust
rust:
  - nightly
  - beta
  - stable

script:
  - cargo build --verbose -p telegram-bot-raw
  - cargo test --verbose -p telegram-bot-raw

after_success:
  - |
        test ${TRAVIS_PULL_REQUEST} == "false" && \
        test ${TRAVIS_BRANCH} == "master" && \
        test "${TRAVIS_BUILD_NUMBER}.3" == "${TRAVIS_JOB_NUMBER}" && \
        bash deploy.sh
